//Generates a static list of .html files in _parcel-links.html for parcel to manage

var fs = require("fs");
var path = require("path");

const IGNORE_DIRS = ['node_modules']

var srcDir = path.resolve(__dirname, "../");

function walk(dir, ext) {
  var results = [];
  var list = fs.readdirSync(dir);
  list.forEach(name => {
    var file = path.join(dir, name);
    var stat = fs.statSync(file);
    if (stat && stat.isDirectory()) {
      if (IGNORE_DIRS.indexOf(name) == -1) {
        results = results.concat(walk(file, ext));
      }
    } else if (file.endsWith(ext)) {
      results.push(file);
    }
  });
  return results;
}

var results = walk(srcDir, ".html");

var sb = "<!-- generated by scripts/pre-build.js -->\n\n";
results.forEach(filePath => {
  var relativePath = filePath.substring(srcDir.length + 1);
  sb += `<a href="${relativePath}"></a>\n`;
});

var toFile = path.join(srcDir, "_parcel-links.html");
fs.writeFileSync(toFile, sb);
